# Generated by Django 2.2.10 on 2021-08-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='posting_date',
            field=models.DateField(null=True),
        ),
    ]
