# Generated by Django 2.2.10 on 2021-09-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(auto_created=True, null=True, verbose_name='Posting Date')),
                ('code', models.CharField(help_text='Scan your Queue Code', max_length=10, verbose_name='Queue Code')),
                ('rating', models.IntegerField(help_text='Input 1 to 5  only')),
                ('impression', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
