# Generated by Django 2.2.10 on 2021-09-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='impression',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Worst', 'Worst')], max_length=20),
        ),
    ]
