# Generated by Django 2.2.10 on 2021-09-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_rating',
            name='updated_by',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_by',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='sub_rating',
            name='created_by',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
