# Generated by Django 2.2.10 on 2021-09-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210913_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='posting_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Posting Date'),
        ),
    ]
