# Generated by Django 3.2.7 on 2021-09-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_sub_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_rating',
            name='sub_rating',
            field=models.CharField(max_length=255),
        ),
    ]
