# Generated by Django 3.2.7 on 2021-09-25 10:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_sub_rating_sub_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_rating',
            name='created_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=20),
        ),
        migrations.AlterField(
            model_name='sub_rating',
            name='updated_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated_by',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=20),
        ),
    ]
