# Generated by Django 2.2.10 on 2021-09-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210913_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='comments',
            field=models.TextField(max_length=255),
        ),
    ]
