# Generated by Django 3.2.7 on 2021-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210925_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_rating',
            name='created_by',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sub_rating',
            name='updated_by',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated_by',
            field=models.CharField(max_length=20),
        ),
    ]
