# Generated by Django 2.2.10 on 2021-09-15 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20210914_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='rating',
            field=models.IntegerField(default=0, help_text='Input 1 to 5  only', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
